# Generated by Django 4.2.1 on 2024-06-09 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='mesa',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
