# Generated by Django 4.2.1 on 2024-06-10 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_pedido_mesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='quantidade',
            field=models.PositiveBigIntegerField(default=1),
        ),
    ]
